### ISSUE TITLE
Wrong ClusterRole permission

### ISSUE THREAD

**Issue by tehKapa** [elastic/azure-marketplace#316]
Hi! 
Using this [manifest](https://raw.githubusercontent.com/elastic/beats/7.4/deploy/kubernetes/metricbeat-kubernetes.yaml), I have found permission problems on AKS.

```
Failed to list *v1beta1.Replica Set: replica sets.apps is forbidden: User "system:serviceaccount:kube-system:metricbeat" cannot list resource "replicasets" in API group "apps" at the cluster scopeStreaming new entries 
```

It is easily solved by adding the resource replicasets in the apiGroups "apps". Line 330

```
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - replicasets
  - deployments
  verbs: ["get", "list", "watch"]

```

I hope it'll help.
