### ISSUE TITLE
Incorrect monitoring and SSL configuration in logstash.yml with Logstash deployment

### ISSUE THREAD

**Issue by quimrodri** [elastic/azure-marketplace#337]
Hi!

Deploying a cluster with a Logstash machine we have found that the monitoring section for Logstash configuration (/etc/logstash/logstash.yml) is incorrect. It's like this:
```yaml
xpack.monitoring.elasticsearch.hosts: ["${ELASTICSEARCH_URL}"]
xpack.monitoring.elasticsearch.ssl.certificate_authority: "${ELASTICSEARCH_CACERT}"
xpack.monitoring.elasticsearch.ssl.verification_mode: none
xpack.monitoring.enabled: true
```

Notice the bash variables ELASTICSEARCH_URL and ELASTICSEARCH_CACERT have not been replaced by their values.
