### ISSUE TITLE
Logstash incorrect configuration file

### ISSUE THREAD

**Issue by quimrodri** [elastic/azure-marketplace#341]
Hi!

We have observed that after installing the cluster without X-Pack license and ELK version > 7.0 the Logstash configuration is not correct.

Logstash gives this error all the time:
```
[2020-05-12T15:17:17,700][ERROR][logstash.licensechecker.licensereader] Unable to retrieve license information from license server {:message=>"Got response code '401' contacting Elasticsearch at URL 'https://10.120.25.250:9200/_xpack'"}
[2020-05-12T15:17:17,960][ERROR][logstash.monitoring.internalpipelinesource] Failed to fetch X-Pack information from Elasticsearch. This is likely due to failure to reach a live Elasticsearch cluster.
```
And the configuration is like this:

```yml
node.name: "logstash-0"
path.data: /var/lib/logstash
path.config: /etc/logstash/conf.d/*.conf
path.logs: /var/log/logstash
log.level: error
xpack.monitoring.elasticsearch.hosts: ["${ELASTICSEARCH_URL}"]
xpack.monitoring.elasticsearch.ssl.certificate_authority: "${ELASTICSEARCH_CACERT}"
xpack.monitoring.elasticsearch.ssl.verification_mode: none
xpack.monitoring.enabled: true
```
It seems that the xpack.monitoring.elasticsearch.username and xpack.monitoring.elasticsearch.password part is missing from the configuration file. After adding it the error goes away.

It seems that the problem could be that the case of having BASIC_SECURITY enabled without having INSTALL_XPACK is not taken into account here:
https://github.com/elastic/azure-marketplace/blob/2b322496fd3c0f4f1fd5222a7127df917851a330/src/scripts/logstash-install.sh#L274-L292

When INSTALL_XPACK is false (as in our case) it will not add the username and password so the connection to the cluster will fail.

Maybe it could be something like this:

```bash
    # configure Monitoring
    if dpkg --compare-versions "$LOGSTASH_VERSION" "lt" "7.0.0"; then
      echo "xpack.monitoring.elasticsearch.url: \"${ELASTICSEARCH_URL}\"" >> $LOGSTASH_CONF
    else
      echo "xpack.monitoring.elasticsearch.hosts: [\"${ELASTICSEARCH_URL}\"]" >> $LOGSTASH_CONF
    fi
    
    # configure monitoring credentials if Security is enabled
    if [[ ${INSTALL_XPACK} -ne 0 || ${BASIC_SECURITY} -ne 0 ]]; then
      echo "xpack.monitoring.elasticsearch.username: logstash_system" >> $LOGSTASH_CONF
      echo "xpack.monitoring.elasticsearch.password: \"${LOGSTASH_SYSTEM_PASSWORD}\"" >> $LOGSTASH_CONF
    fi
```

I just extracted the logic of adding elastisearch.url from the first if (as it was done always anyway) and added another condition taking into account BASIC_SECURITY to add the username and password.
